#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

clear

# oh-my-zsh

printf "Do you want to install oh-my-zsh?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) rm -rf ~/.oh-my-zsh/;
	      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)";
              break;;
        No ) break;;
    esac
done

clear

# zsh

printf "Do you want to install zsh?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) 
              rm -rf ~/.zshrc;
              rm -rf ~/.zprofile;
              ln -s ${BASEDIR}/zshrc ~/.zshrc;
              ln -s ${BASEDIR}/zprofile ~/.zprofile;
              break;;
        No ) break;;
    esac
done

clear

# kitty

printf "Do you want to install kitty config files?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) 
              rm -rf ~/.config/kitty/;
              ln -s ${BASEDIR}/kitty/ ~/.config/;
              break;;
        No ) break;;
    esac
done

clear

# neofetch

printf "Do you want to install neofetch config files?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) rm -rf ~/.config/neofetch/;
              ln -s ${BASEDIR}/neofetch/ ~/.config/;
              break;;
        No ) break;;
    esac
done

clear

printf "Do you want to install st(Simple Terminal)?\n"
printf "\n"
if [[ "$(id -u)" -ne 0 ]]; then 
    printf "Please run as root\n\n"
    read -p "Press any key to continue"
    exit
fi
select yn in "Yes" "No"; do
    case $yn in
        Yes ) ln -s ${BASEDIR}/st /usr/bin/st
              ln -s ${BASEDIR}/st /usr/lib/st
	      exit;;
	No ) exit;;
    esac
done
