#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

clear

# Dependencies

printf "Do you want run Arch install scripts?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) git clone https://aur.archlinux.org/paru-bin;
			cd paru-bin;
			makepkg -si;
	      paru -S hyprland mate-polkit ffmpeg neovim viewnior rofi pavucontrol thunar starship wl-clipboard wf-recorder swww grimblast-git ffmpegthumbnailer tumbler playerctl noise-suppression-for-voice thunar-archive-plugin alacritty aylurs-gtk-shell wlogout sddm pamixer nwg-look nordic-theme papirus-icon-theme dunst noto-fonts noto-fonts-emoji brightnessctl hyprpicker-git hyprlock winboat-bin;
              break;;
        No ) break;;
    esac
done

clear


# oh-my-zsh

printf "Do you want to install oh-my-zsh?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) rm -rf ~/.oh-my-zsh/;
	      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)";
              break;;
        No ) break;;
    esac
done

clear


# zsh

printf "Do you want to install zsh?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) 
              rm -rf ~/.zshrc;
              rm -rf ~/.zprofile;
              ln -s ${BASEDIR}/zshrc ~/.zshrc;
              ln -s ${BASEDIR}/zprofile ~/.zprofile;
              break;;
        No ) break;;
    esac
done

clear

# kitty

printf "Do you want to install kitty config files?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) 
              rm -rf ~/.config/kitty/;
              ln -s ${BASEDIR}/kitty/ ~/.config/;
              break;;
        No ) break;;
    esac
done

clear

# neofetch

printf "Do you want to install neofetch config files?\n"
select yn in "Yes" "No"; do
    case $yn in
        Yes ) rm -rf ~/.config/neofetch/;
              ln -s ${BASEDIR}/neofetch/ ~/.config/;
              break;;
        No ) break;;
    esac
done

clear

printf "Do you want to install st(Simple Terminal)?\n"
printf "\n"
if [[ "$(id -u)" -ne 0 ]]; then 
    printf "Please run as root\n\n"
    read -p "Press any key to continue"
    exit
fi
select yn in "Yes" "No"; do
    case $yn in
        Yes ) cd ${BASEDIR}/st/ && make clean install
	      exit;;
	No ) exit;;
    esac
done
